对应博客2.2.4节,最终得出的结论是:
* 如果用像素值(0-255整数)表示图片数据, 那么一律将其数据类型设置成uint8,避免不必要的bug

In [1]:
import pandas as pd
import numpy as np
import ast

from PIL import Image
from torchvision import transforms


from data_loader import *

input_dir = "../../input"

In [2]:
test = pd.read_csv(os.path.join(input_dir, "test_simplified.csv"), nrows=40)
test.head()

key_id countrycode  \
0  9000003627287624          DE   
1  9000010688666847          UA   
2  9000023642890129          BG   
3  9000038588854897          US   
4  9000052667981386          AR   

                                             drawing  
0  [[[17, 18, 20, 25, 137, 174, 242, 249, 251, 25...  
1  [[[174, 145, 106, 38, 11, 4, 4, 15, 29, 78, 16...  
2  [[[0, 12, 14, 17, 16, 24, 55, 57, 60, 79, 82, ...  
3  [[[0, 9, 23, 40, 54, 60, 81, 105, 123, 167, 20...  
4  [[[87, 82, 71, 63, 66, 92, 96, 95], [220, 218,...

In [3]:
index = 1
drawing = test.loc[index,"drawing"]
drawing_list = ast.literal_eval(drawing)

In [4]:
image_array = drawing_list_to_array(drawing_list, size=299, channel=3, point_drop_prob=0.0)
image_array[image_array != 0.0][:10]

array([ 19.,  19.,  19., 238., 238., 238., 255., 255., 255., 255.])

In [5]:
print("数据类型:", image_array.dtype)
# train
train_transforms = transforms.Compose([transforms.ToTensor(),
                                       # transforms.Normalize(mean=[0.5, 0.5, 0.5], std=[0.5, 0.5, 0.5] )
                                      ])
                                              
# train_input = train_transforms(np.copy(image_array).astype("uint8"))
train_input = train_transforms(np.copy(image_array))
train_input[train_input != 0.0][:10]

数据类型: float64


tensor([  19.,  238.,  255.,  255.,  255.,  255.,  255.,  255.,  255.,
         255.], dtype=torch.float64)

In [6]:
# test
test_transforms = transforms.Compose([transforms.ToPILImage(),
                                       transforms.ToTensor(),
                                       # transforms.Normalize(mean=[0.5, 0.5, 0.5], std=[0.5, 0.5, 0.5])
                                     ])

test_input = test_transforms(np.copy(image_array).astype("uint8")) # "uint8" 等价于 np.uint8

test_input[test_input != 0.0][:10]

tensor([ 0.0745,  0.9333,  1.0000,  1.0000,  1.0000,  1.0000,  1.0000,
         1.0000,  1.0000,  1.0000])